-- 코드를 입력하세요
SELECT T1.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO  T1
JOIN REST_REVIEW T2 ON T1.REST_ID = T2.REST_ID
WHERE t1.ADDRESS LIKE '서울%'
GROUP BY T1.REST_ID
ORDER BY SCORE DESC, T1.VIEWS DESC
