-- 코드를 입력하세요
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, 
(CASE WHEN ISNULL(FREEZER_YN)
THEN 'N'
ELSE FREEZER_YN
END) as FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME LIKE '창고_경기%'
ORDER BY WAREHOUSE_ID