-- 코드를 입력하세요
SELECT T1.PRODUCT_ID, PRODUCT_NAME, SUM(T1.PRICE * T2.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT T1
JOIN FOOD_ORDER T2
      ON T1.PRODUCT_ID = T2.PRODUCT_ID
WHERE  PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, T1.PRODUCT_ID 