SELECT INGREDIENT_TYPE, sum(TOTAL_ORDER) as TOTAL_ORDER
from FIRST_HALF
left join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
group by ICECREAM_INFO.INGREDIENT_TYPE
order by  FIRST_HALF.TOTAL_ORDER
