-- 코드를 입력하세요
SELECT T1.TITLE, T1.BOARD_ID, T2.REPLY_ID, T2.WRITER_ID, T2.CONTENTS, DATE_FORMAT(T2.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD as T1
join USED_GOODS_REPLY as T2 on T1.BOARD_ID = T2.BOARD_ID
where T1.CREATED_DATE between '2022-10-01' and '2022-10-31'
order by T2.CREATED_DATE, T1.TITLE 
